development:
  address: "smtp.gmail.com"
  port: 587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: "example@gmail.com"
  password: "123456"
  enable_starttls_auto: true
production:
  address: "smtp.mailgun.org"
  port: 587"
  domain: "ihower.com"
  authentication: "plain"
  user_name: "postmaster@ihower.tw"
  password: "1234567890"
  enable_starttls_auto: true
