development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "example@gmail.com"
  password: "123456"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "example@gmail.com"
  password: "123456"
  enable_starttls_auto: true
  address: "smtp.mailgun.org"
