development:
  secret_key_base: 464fc4de67c360467ac5ac9f942f6fe3af4735502cc1953e4c84e68e0acdaf08a8a79a6a7c083983adf0d3621cb7bda8779fb9374f860ebdc1cca7fec0a386c3
  action_mailer:
    :default:
      :from: example@gmail.com
      :reply_to: example@gmail.com
  redis:
    :url: redis://localhost:6379
test:
  secret_key_base: d605f2e214e6862cf116a7d973b7ae0c0c42b37573ac28c0f64ac3cb95eb48080a4dc4d1f83079308673209f0c45d51a5d0c9de291d8381d1997ecc7a2a90df7

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  action_mailer:
    :default:
      :from: example@gmail.com
      :reply_to: example@gmail.com
  redis:
    :url: redis://localhost:6379
