# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 464fc4de67c360467ac5ac9f942f6fe3af4735502cc1953e4c84e68e0acdaf08a8a79a6a7c083983adf0d3621cb7bda8779fb9374f860ebdc1cca7fec0a386c3

test:
  secret_key_base: d605f2e214e6862cf116a7d973b7ae0c0c42b37573ac28c0f64ac3cb95eb48080a4dc4d1f83079308673209f0c45d51a5d0c9de291d8381d1997ecc7a2a90df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
